
export const REQUEST_ALL_POSTS = 'REQUEST_ALL_POSTS';
export const RECEIVE_ALL_POSTS = 'RECEIVE_ALL_POSTS';

export const REQUEST_POSTS_BY_CATEGORY = 'REQUEST_POSTS_BY_CATEGORY';
export const RECEIVE_POSTS_BY_CATEGORY = 'RECEIVE_POSTS_BY_CATEGORY';

export const REQUEST_POST_BY_ID = 'REQUEST_POST_BY_ID';
export const RECEIVE_POST_BY_ID = 'RECEIVE_POST_BY_ID';

export const SET_CATEGORY = 'SELECT_CATEGORY'

export const REQUEST_CREATE_POST = 'REQUEST_CREATE_POST ';
export const RECEIVE_CREATE_POST = 'RECEIVE_CREATE_POST';

export const REQUEST_EDIT_POST = 'REQUEST_EDIT_POST ';
export const RECEIVE_EDIT_POST = 'RECEIVE_EDIT_POST';

export const REQUEST_POST_DETAIL = 'REQUEST_POST_DETAIL';
export const RECEIVE_POST_DETAIL = 'RECEIVE_POST_DETAIL';

export const REQUEST_DELETE_ITEM = 'REQUEST_DELETE_POST';
export const RECEIVE_DELETE_ITEM = 'RECEIVE_DELETE_POST';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const Categories = {
  SET_ALL: "all",
  SET_REACT: "react",
  SET_REDUX: "redux",
  SET_UDACITY: "udacity"
};
