export const ERROR_STATE = "ERROR_STATE";
export const LOAD_POSTS_REQUEST = "LOAD_POSTS_REQUEST";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_FAILURE = "LOAD_POST_FAILURE";

export const LOAD_POSTS_BY_CATEGORY_REQUEST = "LOAD_POSTS_BY_CATEGORY_REQUEST";
export const LOAD_POSTS_BY_CATEGORY_FAILURE = "LOAD_POSTS_BY_CATEGORY_FAILURE";
export const LOAD_POSTS_BY_CATEGORY_SUCCESS = "LOAD_POSTS_BY_CATEGORY_SUCCESS";

export const LOAD_POST_BY_ID_REQUEST = "LOAD_POST_BY_ID_REQUEST";
export const LOAD_POST_BY_ID_FAILURE = "LOAD_POST_BY_ID_FAILURE";
export const LOAD_POST_BY_ID_SUCCESS = "LOAD_POST_BY_ID_SUCCESS";

export const SET_CATEGORY = "SELECT_CATEGORY";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const EDIT_POST_REQUEST = "EDIT_POST_REQUEST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_FAILURE = "EDIT_POST_FAILURE";

export const POST_VOTE_REQUEST = "POST_VOTE_REQUEST";
export const POST_VOTE_SUCCESS = "POST_VOTE_SUCCESS";
export const POST_VOTE_FAILURE = "POST_VOTE_FAILURE";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const LOAD_CATEGORIES_REQUEST = "LOAD_CATEGORIES_REQUEST";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";

export const Categories = {
  SET_ALL: "all",
  SET_REACT: "react",
  SET_REDUX: "redux",
  SET_UDACITY: "udacity"
};

export const LOAD_COMMENTS_BY_POST_ID_REQUEST =
  "LOAD_COMMENTS_BY_POST_ID_REQUEST";
export const LOAD_COMMENTS_BY_POST_ID_SUCCESS =
  "LOAD_COMENTS_BY_POST_ID_SUCCESS";

export const LOAD_COMMENT_BY_ID_REQUEST = "LOAD_COMMENT_BY_ID_REQUEST";
export const LOAD_COMMENT_BY_ID_SUCCESS = "LOAD_COMENT_BY_ID_SUCCESS";

export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";

export const EDIT_COMMENT_REQUEST = "EDIT_COMMENT_REQUEST ";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";

export const COMMENT_VOTE_REQUEST = "COMMENT_VOTE_REQUEST";
export const COMMENT_VOTE_SUCCESS = "COMMENT_VOTE_SUCCESS";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
